services:
  - name: docker:dind
    # explicitly disable tls to avoid docker startup interruption
    command: ["--tls=false"]

variables:
  PROJECT_NAME: 'Gamestore'
  DOCKER_HOST: "tcp://localhost:2375"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

test:
  image: mcr.microsoft.com/dotnet/sdk:8.0
  stage: test
  script:
    - 'cd $PROJECT_NAME'
    - 'dotnet test --collect:"XPlat Code Coverage" --results-directory artifacts/test_results/ /p:CollectCoverage=true /p:Threshold=50 /p:ThresholdStat=total /p:ExcludeByFile="**/Migrations/*"' 
  coverage: '/Total\s*\|\s*(\d+(?:\.\d+)?)/'
  artifacts:
    paths:
      - '$PROJECT_NAME/artifacts/test_results/*/coverage.cobertura.xml'
    reports:
      coverage_report:
        coverage_format: cobertura
        path: '$PROJECT_NAME/artifacts/test_results/*/coverage.cobertura.xml'